### ISSUE TITLE
pinout for arduino uno

### ISSUE THREAD

**Issue by tonyt321** [Gigahawk/clickwheel_sample_firmware#2]
![312f525e-bfe9-4df3-91d2-0bc9753de883](https://user-images.githubusercontent.com/34804458/156655060-f4d234d7-3461-458f-915e-e15a63f3cdd3.jpg)

Hello I am trying to use this to be able to read out to an arduino Uno but am struggling to get an output 
 
I have this in the main.cpp for pin definitions any help would be appreciated 

#define CW_SDA_PIN 3              // click wheel SDA pin
#define CW_SCL_PIN 2 //INT1       // click wheel SCL pin

**Comment by Gigahawk** [comment]
This implementation is considered obselete, you can just setup your Arduino as a SPI slave to read the data instead.

See https://github.com/Gigahawk/clickwheel_reverse_eng for the details
